import Head from "next/head";
import Image from "next/image";

import {
  Activity,
  Collection,
  Content,
  Drops,
  Headers,
  HeadList,
  Search,
  SearchBar,
  Sidebar,
} from "../../components";
export default function slug() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        <Headers />
        <div className="bg-black flex h-full">
          <div className="w-3/12 h-full p-3">
            <Sidebar />
          </div>
          <div className="w-6/12 p-3">
            <Collection />
          </div>
          <div className="w-3/12 p-3">
            <SearchBar />
            <Activity />
          </div>
        </div>
      </div>
    </div>
  );
}
