import React from "react";
import Head from "next/head";
import Image from "next/image";
import { useContext, useEffect, useState } from "react";
import {
  Content,
  Drops,
  Footer,
  Headers,
  MyDashboard,
  SearchBar,
  Sidebar,
} from "../components";
import { AppContext } from "../context";
import styles from "../styles/Home.module.css";
function portofolio() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col  bg-black h-[100vh]">
        <Headers connect />
        <div className="bg-black flex ">
          <div className="md:w-3/12 w-2/12  p-3 pb-0">
            <Sidebar />
          </div>
          <div className="md:w-6/12 grow p-3">
            <MyDashboard />
          </div>
          <div className="w-3/12 p-3 hidden md:block">
            <Drops />
          </div>
        </div>
        <div>
          <Footer />
        </div>
      </div>
    </div>
  );
}

export default portofolio;
